const counties = [
    'Albany', 
    'Allegany',
    'Atlantic',
    'Bergen',
    'Burlington',
    'Bronx', 
    'Broome', 
    'Cattaraugus', 
    'Cayuga',
    'Camden',
    'Chautauqua', 
    'Chemung', 
    'Cumberland',
    'Cape May',
    'Chenango', 
    'Clinton', 
    'Columbia', 
    'Cortland', 
    'Delaware', 
    'Dutchess', 
    'Erie', 
    'Essex NY', 
    'Essex NJ',
    'Franklin', 
    'Fulton', 
    'Genesee', 
    'Gloucester',
    'Greene', 
    'Hamilton',
    'Hudson', 
    'Herkimer',
    'Hunterdon', 
    'Jefferson', 
    'Kings',
    'Lewis', 
    'Livingston', 
    'Madison', 
    'Mercer',
    'Morris',
    'Monroe', 
    'Montgomery', 
    'Middlesex',
    'Monmouth',
    'Nassau', 
    'New York',
    'Niagara', 
    'Oneida', 
    'Onondaga', 
    'Ontario', 
    'Orange',
    'Ocean', 
    'Orleans', 
    'Oswego', 
    'Otsego', 
    'Putnam',
    'Passaic', 
    'Queens', 
    'Rensselaer', 
    'Richmond',
    'Rockland', 
    'Saint Lawrence', 
    'Saratoga', 
    'Schenectady', 
    'Schoharie', 
    'Schuyler', 
    'Seneca', 
    'Steuben', 
    'Suffolk', 
    'Sullivan',
    'Salem', 
    'Somerset',
    'Sussex',
    'Tioga', 
    'Tompkins', 
    'Ulster',
    'Union', 
    'Warren NY', 
    'Warren NJ',
    'Washington', 
    'Wayne', 
    'Westchester', 
    'Wyoming', 
    'Yates', 
];

export default counties;