const softSkills = [
    'Communication',
    'Teamwork',
    'Problem-solving',
    'Time management', 
    'Leadership',
    'Adaptability',
    'Creativity',
    'Empathy',
    'Conflict resolution',
    'Active listening',
    'Critical thinking',
    'Cultural competence',
    'Customer service',
    'Emotional intelligence',
    'Flexibility',
    'Goal-setting',
    'Interpersonal skills',
    'Negotiation',
    'Patience',
    'Persuasion',
    'Positive attitude',
    'Presentation skills',
    'Problem analysis',
    'Self-motivation',
    'Stress management',
    'Trustworthiness',
    'Verbal communication',
    'Writing',
    'Attention to detail',
    'Coaching and mentoring',
    'Conflict management',
    'Cultural awareness',
    'Decision-making',
    'Dependability',
    'Diversity and inclusion',
    'Enthusiasm',
    'Financial management',
    'Humility',
    'Initiative',
    'Innovation',
    'Intercultural communication',
    'Interpersonal communication',
    'Learning agility',
    'Organizational skills',
    'Resilience',
    'Strategic thinking',
    'Work ethic' 
];

export default softSkills;